# -*- coding: utf-8 -*-
"""Sistema de Recomendações

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SmOrLN94bI12a-xvUrLmcw5eEJmfVDH
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, GlobalAveragePooling2D, Dropout, Dense
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from shutil import move
from tqdm import tqdm

# Limpeza de pastas antigas para evitar confusão
!rm -rf /content/Fashion_data

print("Bibliotecas importadas e ambiente limpo.")

# Commented out IPython magic to ensure Python compatibility.
# #Hide
# %%writefile kaggle.json
# {"username":"<your kaggle username>","key":"<your kaggle api key>"}

import os
import pandas as pd
from shutil import move
from tqdm import tqdm

# 1. Download e Extração
!kaggle datasets download -d paramaggarwal/fashion-product-images-small
!unzip -o fashion-product-images-small.zip -d /content/

# 2. Organização em pastas de categorias
csv_path = '/content/styles.csv'
images_src = '/content/images/'
dest_base = '/content/Fashion_data/categories'

os.makedirs(dest_base, exist_ok=True)

try:
    df = pd.read_csv(csv_path, usecols=['id','masterCategory'], on_bad_lines='skip')
    df['id'] = df['id'].astype('str')

    all_imgs = [f for f in os.listdir(images_src) if f.endswith('.jpg')]
    print(f"Movendo {len(all_imgs)} imagens para pastas de categorias...")

    for img in tqdm(all_imgs):
        img_id = img.split('.')[0]
        res = df[df['id'] == img_id]
        if not res.empty:
            cat = str(res['masterCategory'].values[0])
            cat_path = os.path.join(dest_base, cat)
            if not os.path.exists(cat_path): os.makedirs(cat_path)
            move(os.path.join(images_src, img), os.path.join(cat_path, img))
    print("\nDados organizados com sucesso!")
except Exception as e:
    print(f"Aviso: {e}. As imagens podem já ter sido movidas.")

import tensorflow as tf
import os

data_path = '/content/Fashion_data/categories'
cats = sorted([d for d in os.listdir(data_path) if os.path.isdir(os.path.join(data_path, d))])

gen_params = dict(rescale=1./255, validation_split=0.2)
flow_params = dict(target_size=(224, 224), batch_size=32, interpolation='bilinear')

# Geradores simplificados
train_gen = tf.keras.preprocessing.image.ImageDataGenerator(rotation_range=20, horizontal_flip=True, **gen_params).flow_from_directory(data_path, subset='training', shuffle=True, **flow_params)
valid_gen = tf.keras.preprocessing.image.ImageDataGenerator(**gen_params).flow_from_directory(data_path, subset='validation', shuffle=False, **flow_params)
full_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255).flow_from_directory(data_path, shuffle=False, **flow_params)

# 1. Definição Única do Modelo (Standardized naming)
base_model = tf.keras.applications.ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False # Inicialmente congelado

x = tf.keras.layers.GlobalAveragePooling2D()(base_model.output)
x = tf.keras.layers.Dropout(0.2)(x)
embedding_layer = tf.keras.layers.Dense(512, activation='relu', name='embedding_layer')(x)
predictions = tf.keras.layers.Dense(len(cats), activation='softmax', name='predictions')(embedding_layer)

model = tf.keras.models.Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Extrator de features padronizado referenciando a camada interna
feature_extractor = tf.keras.models.Model(inputs=model.input, outputs=model.get_layer('embedding_layer').output)

print("Modelo e feature_extractor únicos definidos. Base inicial congelada.")

print("Etapa 1: Treinando apenas as camadas superiores...")
model.fit(train_gen, epochs=2, validation_data=valid_gen)

print("\nEtapa 2: Fine-tuning global (descongelando com LR reduzido)...")
base_model.trainable = True
# LR muito baixo para não destruir os pesos pré-treinados
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), loss='categorical_crossentropy', metrics=['accuracy'])

callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2, restore_best_weights=True, monitor='val_accuracy'),
    tf.keras.callbacks.ModelCheckpoint('/content/best_model.keras', save_best_only=True, monitor='val_accuracy')
]

# Corrigido: instância 'model', vírgulas adicionadas e 'valid_gen' correto
model.fit(train_gen, epochs=3, validation_data=valid_gen, callbacks=callbacks)

from sklearn.neighbors import NearestNeighbors
import numpy as np

# 1. Extração de características (usando o extrator único definido anteriormente)
print("Extraindo embeddings de todas as imagens para o motor de busca...")
# 'full_gen' contém as 44k imagens organizadas
all_features = feature_extractor.predict(full_gen, verbose=1)
all_filenames = full_gen.filenames

# 2. Treinar o modelo de vizinhos próximos (Nearest Neighbors)
nn_model = NearestNeighbors(n_neighbors=6, algorithm='auto', metric='cosine').fit(all_features)

print("Motor de busca indexado com sucesso!")

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity
from PIL import Image

# 2. Gerar embeddings usando o extrator padronizado
print("Extraindo embeddings visuais...")
embeddings = feature_extractor.predict(valid_gen, verbose=1)
filenames = valid_gen.filenames
labels = valid_gen.classes

def plot_recommendations(query_idx, embeddings, filenames, data_path, top_n=5):
    query_vec = embeddings[query_idx].reshape(1, -1)
    sims = cosine_similarity(query_vec, embeddings).flatten()
    indices = np.argsort(-sims)[1:top_n+1]

    plt.figure(figsize=(20, 4))
    plt.subplot(1, top_n + 1, 1)
    plt.imshow(Image.open(os.path.join(data_path, filenames[query_idx])))
    plt.title("CONSULTA")
    plt.axis('off')

    for i, idx in enumerate(indices):
        plt.subplot(1, top_n + 1, i + 2)
        plt.imshow(Image.open(os.path.join(data_path, filenames[idx])))
        plt.title(f"Sim {i+1} ({sims[idx]:.2f})")
        plt.axis('off')
    plt.show()

query_idx = np.random.randint(0, len(filenames))
plot_recommendations(query_idx, embeddings, filenames, '/content/Fashion_data/categories')

import gradio as gr
from PIL import Image

def recommend_v3(img_input):
    # Preprocessamento da imagem de entrada
    img = np.array(img_input.resize((224, 224))) / 255.0
    if img.shape[-1] == 4: img = img[:,:,:3]

    # Extração do vetor de características
    query_vec = feature_extractor.predict(img[np.newaxis], verbose=0)

    # Busca pelos vizinhos mais próximos
    distances, indices = nn_model.kneighbors(query_vec)

    # Retorna as 5 imagens mais similares
    return [Image.open(os.path.join(data_path, all_filenames[i])) for i in indices[0][:5]]

gradio_interface = gr.Interface(
    fn=recommend_v3,
    inputs=gr.Image(type='pil'),
    outputs=[gr.Image() for _ in range(5)],
    title="Fashion Search AI - Full Catalog"
)
gradio_interface.launch(share=True)